# Generated by Django 5.1.3 on 2024-12-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_workout_exercise'),
        ('tracker', '0004_trainer_usertrainer'),
    ]

    operations = [
    ]
